### ISSUE TITLE
忘记写上传静态网页到S3

### ISSUE THREAD

**Issue by a211212abc** [Hanyang-Li/BotFarmer-1point3acres#1]
很好的repo，感谢大佬！

不过在S3的部分好像忘了写把静态网页上传到S3储存桶，而且希望把示例user文件夹的名字改成user_name_1，这样就不会忘记改文件夹名了

**Comment by Hanyang-Li** [comment]
感谢支持🙏

确实README中在提到修改config后忘记写把所有文件上传到桶里了，感谢提醒（竟然耐心读我的流水账，震惊hhh）

感谢对user文件夹中事例名字提出的建议，这样确实可以提醒这些事例文件夹是需要改成`user_name`的，我已经对相关文件夹和README中的对应部分进行了调整

**Comment by a211212abc** [comment]
hhhhh跟着readme简单入门了下aws美滋滋（抱拳了
